version: 2

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache--{{checksum "package-lock.json"}}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache--{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Heroku login
          command: heroku container:login
      - run:
          name: Push container
          command: heroku container:push web --app ${HEROKU_APP}
      - run:
          name: Release container
          command: heroku container:release web --app ${HEROKU_APP}

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
